export const CAMPANHA_COLUNAS_SELECT = [
  'id_campanha',
  'id_usuario',
  'id_admin',
  'id_area_conhecimento',
  'titulo',
  'modelo',
  'meta_financeira',
  'valor_bruto_arrecadado',
  'taxa_plataforma',
  'descricao',
  'data_inicio',
  'data_fim',
  'status',
  'aprovado_em',
  'encerrado_em',
  'video_apresentacao_url',
  'criado_em',
] as const;
