/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type FaseAtualizacao = "andamento" | "resultado_final" | "resultado_preliminar";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MeioPagamento = "boleto" | "cartao_credito" | "cartao_debito" | "pix";

export type ModeloCampanha = "all-or-nothing" | "flexivel";

export type Numeric = ColumnType<string, number | string, number | string>;

export type StatusCampanha = "aguardando_aprovacao" | "ativo" | "encerrado" | "encerrado_moderacao" | "nao_atingido" | "rascunho" | "rejeitado" | "sucesso";

export type StatusContribuicao = "a_devolver" | "confirmado" | "devolvido" | "erro" | "expirado" | "pendente" | "reembolsado" | "reembolso_manual" | "repassado";

export type StatusDenuncia = "em_analise" | "improcedente" | "pendente" | "resolvida";

export type StatusEncerramento = "aprovado" | "cancelado" | "pendente" | "rejeitado";

export type StatusNotificacao = "cancelado" | "enviado" | "falhou" | "pendente";

export type StatusPesquisador = "ativo" | "suspenso";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TipoAtualizacao = "imagem" | "linkexterno" | "pdf" | "texto";

export type TipoConfiguracao = "booleano" | "decimal" | "inteiro" | "texto";

export type TipoMotivoDenuncia = "campanha" | "perfil";

export type TipoRecompensa = "acesso_antecipado" | "digital" | "reconhecimento";

export type TipoTermo = "cadastro" | "upgrade_pesquisador";

export type TipoVinculo = "independente" | "institucional";

export type TituloAcademico = "doutor" | "especialista" | "graduado" | "mestre";

export interface AceiteTermoContribuicao {
  aceito_em: Generated<Timestamp>;
  id_aceite_contrib: Generated<number>;
  id_contribuicao: number;
  id_termo: number;
  ip_aceite: string | null;
}

export interface AreaConhecimento {
  ativo: Generated<boolean>;
  codigo_cnpq: string;
  id_area_conhecimento: Generated<number>;
  id_pai: number | null;
  nome: string;
}

export interface Arquivo {
  ativo: Generated<boolean>;
  chave: string;
  criado_em: Generated<Timestamp>;
  desativado_em: Timestamp | null;
  id_arquivo: Generated<number>;
  id_usuario_upload: number | null;
  nome_original: string;
  tamanho_bytes: number;
  tipo_mime: string;
}

export interface ArquivoAtualizacao {
  id_arq_atu: Generated<number>;
  id_arquivo: number;
  id_atualizacao: number;
}

export interface ArquivoRecompensa {
  id_arq_recompensa: Generated<number>;
  id_arquivo: number;
  id_recompensa: number;
  ordem: number | null;
  principal: Generated<boolean>;
}

export interface AtualizacaoCampanha {
  ativo: Generated<boolean>;
  conteudo: string;
  fase: FaseAtualizacao | null;
  id_atualizacao: Generated<number>;
  id_campanha: number;
  publicado_em: Generated<Timestamp>;
  tipo: TipoAtualizacao | null;
  titulo: string;
}

export interface AuditoriaFinanceira {
  evento: string | null;
  id_auditoria: Generated<number>;
  id_contribuicao: number;
  id_usuario_responsavel: number | null;
  meio_pagamento: MeioPagamento | null;
  status_anterior: string | null;
  status_novo: string;
  timestamp: Generated<Timestamp>;
  valor: Numeric;
}

export interface Campanha {
  aprovado_em: Timestamp | null;
  criado_em: Generated<Timestamp>;
  data_fim: Timestamp | null;
  data_inicio: Timestamp | null;
  descricao: string | null;
  encerrado_em: Timestamp | null;
  enviado_aprovacao_em: Timestamp | null;
  id_admin: number | null;
  id_area_conhecimento: number;
  id_campanha: Generated<number>;
  id_usuario: number;
  meta_financeira: Numeric;
  modelo: Generated<ModeloCampanha>;
  status: Generated<StatusCampanha>;
  taxa_plataforma: Numeric | null;
  titulo: string;
  valor_bruto_arrecadado: Generated<Numeric>;
  video_apresentacao_url: string | null;
}

export interface Comentario {
  ativo: Generated<boolean>;
  conteudo: string;
  criado_em: Generated<Timestamp>;
  endossado: Generated<boolean>;
  id_campanha: number;
  id_comentario: Generated<number>;
  id_pesquisador: number | null;
  ordem_endosso: number | null;
}

export interface Configuracoes {
  ativo: Generated<boolean>;
  chave: string;
  descricao: string | null;
  id_config: Generated<number>;
  id_usuario: number | null;
  publica: Generated<boolean>;
  tipo: TipoConfiguracao;
  valor: string | null;
}

export interface Contribuicao {
  anonima: Generated<boolean>;
  criado_em: Generated<Timestamp>;
  id_campanha: number;
  id_contribuicao: Generated<number>;
  id_transacao_api: string | null;
  id_usuario: number | null;
  meio_pagamento: MeioPagamento;
  status: Generated<StatusContribuicao>;
  token_sessao: Generated<string | null>;
  valor: Numeric;
}

export interface ContribuicaoRecompensa {
  adquirida_em: Generated<Timestamp>;
  id_contrib_recompensa: Generated<number>;
  id_contribuicao: number;
  id_recompensa: number;
  quantidade: Generated<number>;
}

export interface Denuncia {
  criado_em: Generated<Timestamp>;
  id_campanha_alvo: number | null;
  id_denuncia: Generated<number>;
  id_motivo: number;
  id_pesquisador_alvo: number | null;
  id_usuario: number;
  relato: string | null;
  status: Generated<StatusDenuncia>;
}

export interface HistoricoRejeicao {
  id_admin: number | null;
  id_campanha: number;
  id_rejeicao: Generated<number>;
  id_usuario_dono: number;
  justificativa: string | null;
  rejeitado_em: Generated<Timestamp>;
  titulo_campanha: string;
}

export interface LinkAcademico {
  id_link_academico: Generated<number>;
  id_tipolink: number;
  id_usuario: number;
  ordem: number | null;
  rotulo: string | null;
  url: string;
}

export interface LinkAtualizacao {
  id_atualizacao: number;
  id_link_atualizacao: Generated<number>;
  id_tipolink: number;
  ordem: number | null;
  url: string;
}

export interface LinkRecompensa {
  id_link_recompensa: Generated<number>;
  id_recompensa: number;
  id_tipolink: number;
  ordem: number | null;
  url: string;
}

export interface LogAuditoria {
  campos_alterados: string[] | null;
  dados_anteriores: Json | null;
  dados_novos: Json | null;
  id_log: Generated<Int8>;
  id_usuario_responsavel: number | null;
  identidade_registro: string;
  ocorrido_em: Generated<Timestamp>;
  operacao: string;
  tabela: string;
}

export interface MarcoCronograma {
  criado_em: Generated<Timestamp>;
  data_prevista: Timestamp;
  descricao: string | null;
  id_campanha: number;
  id_marco: Generated<number>;
  ordem: Generated<number>;
  titulo: string;
}

export interface MotivoDenuncia {
  ativo: Generated<boolean>;
  descricao: string;
  id_motivo: Generated<number>;
  tipo: TipoMotivoDenuncia;
}

export interface Notificacao {
  criado_em: Generated<Timestamp>;
  email_destinatario: string;
  enviado_em: Timestamp | null;
  id_notificacao: Generated<number>;
  id_usuario: number | null;
  status: Generated<StatusNotificacao>;
  tentativas: Generated<number>;
  tipo_evento: string;
  ultimo_erro: string | null;
}

export interface OrcamentoCampanha {
  categoria: string;
  criado_em: Generated<Timestamp>;
  descricao: string | null;
  id_campanha: number;
  id_orcamento: Generated<number>;
  ordem: Generated<number>;
  valor: Numeric;
}

export interface Papel {
  codigo: string;
  id_papel: Generated<number>;
  nome: string;
}

export interface PapelPermissao {
  id_papel: number;
  id_permissao: number;
}

export interface PerfilPesquisador {
  ativado_em: Timestamp | null;
  cpf_criptografado: string;
  cpf_hash: string;
  id_usuario: number;
  motivo_suspensao: string | null;
  score_atual: Generated<number>;
  score_atualizado_em: Timestamp | null;
  status_pesquisador: Generated<StatusPesquisador>;
  suspenso_ate: Timestamp | null;
  suspenso_por: number | null;
  tipo_vinculo: Generated<TipoVinculo>;
  titulo_academico: TituloAcademico;
  vinculo_institucional: string | null;
}

export interface Permissao {
  id_permissao: Generated<number>;
  nome: string;
}

export interface Recompensa {
  ativo: Generated<boolean>;
  criado_em: Generated<Timestamp>;
  descricao: string | null;
  id_campanha: number;
  id_recompensa: Generated<number>;
  quantidade_disponivel: number | null;
  tipo: TipoRecompensa;
  titulo: string;
  valor_minimo: Numeric;
}

export interface RecuperacaoSenha {
  criado_em: Generated<Timestamp>;
  expira_em: Timestamp;
  id_recuperacao: Generated<number>;
  id_usuario: number;
  token_hash: string;
  usado_em: Timestamp | null;
}

export interface Repasse {
  id_campanha: number;
  id_repasse: Generated<number>;
  meta_atingida: Generated<boolean>;
  repassado_em: Timestamp | null;
  status: string | null;
  taxa_relativa: Numeric | null;
  valor_bruto: Numeric;
  valor_liquido: Numeric;
}

export interface ScoreConfig {
  ativo: Generated<boolean>;
  atualizado_em: Generated<Timestamp>;
  criado_em: Generated<Timestamp>;
  descricao: string | null;
  id_pai: number | null;
  id_score_config: Generated<number>;
  nome: string;
  peso: Numeric;
}

export interface ScorePesquisador {
  calculado_em: Generated<Timestamp>;
  id_rotulo: number | null;
  id_score_config: number;
  id_score_pesq: Generated<number>;
  id_usuario: number;
  motivo: string | null;
  pontos_obtidos: number;
  score_total: number | null;
}

export interface ScoreRotulo {
  ativo: Generated<boolean>;
  atualizado_em: Generated<Timestamp>;
  criado_em: Generated<Timestamp>;
  descricao: string | null;
  id_rotulo: Generated<number>;
  rotulo: string;
  score_maximo: number;
  score_minimo: number;
}

export interface SeguirCampanha {
  id_campanha: number;
  id_seg_campanha: Generated<number>;
  id_usuario: number;
  seguido_em: Generated<Timestamp>;
}

export interface SeguirPesquisador {
  id_pesquisador: number;
  id_seg_pesquisador: Generated<number>;
  id_usuario: number;
  seguido_em: Generated<Timestamp>;
}

export interface Sessao {
  criado_em: Generated<Timestamp>;
  expira_em: Timestamp;
  id_sessao: Generated<number>;
  id_usuario: number;
  ip: string | null;
  origem: Generated<string>;
  refresh_token_hash: string;
  revogado_em: Timestamp | null;
  user_agent: string | null;
}

export interface SolicitacaoEncerramento {
  avaliado_em: Timestamp | null;
  id_admin: number | null;
  id_campanha: number;
  id_solicitacao_encerramento: Generated<number>;
  justificativa_admin: string | null;
  justificativa_pesquisador: string | null;
  solicitado_em: Generated<Timestamp>;
  status: Generated<StatusEncerramento>;
}

export interface TermosDeUso {
  ativo: Generated<boolean>;
  conteudo: string;
  criado_em: Generated<Timestamp>;
  id_termo: Generated<number>;
  tipo: Generated<TipoTermo>;
  versao: string;
}

export interface TipoLink {
  ativo: Generated<boolean>;
  codigo: string;
  dominio: Generated<string[]>;
  id_tipolink: Generated<number>;
  nome: string;
  permite_atualizacao: Generated<boolean>;
  permite_perfil: Generated<boolean>;
  permite_recompensa: Generated<boolean>;
  regex: string | null;
}

export interface Usuario {
  bloqueado_ate: Timestamp | null;
  criado_em: Generated<Timestamp>;
  deletado: Generated<boolean>;
  deletado_em: Timestamp | null;
  deletado_por: number | null;
  email: string;
  email_verificado: Generated<boolean>;
  id_imagem_perfil: number | null;
  id_usuario: Generated<number>;
  motivo_suspensao: string | null;
  nome: string;
  senha_hash: string;
  suspenso_ate: Timestamp | null;
  suspenso_por: number | null;
  tentativas_login_falhas: Generated<number>;
  ultimo_login_em: Timestamp | null;
  ultimo_login_ip: string | null;
}

export interface UsuarioPapel {
  id_papel: number;
  id_usuario: number;
  motivo_suspensao: string | null;
  suspenso_ate: Timestamp | null;
  suspenso_por: number | null;
}

export interface UsuarioTermo {
  aceito_em: Generated<Timestamp>;
  id_termo: number;
  id_usuario: number;
  id_usuario_termo: Generated<number>;
  ip_aceite: string | null;
}

export interface VerificacaoEmail {
  confirmado_em: Timestamp | null;
  criado_em: Generated<Timestamp>;
  expira_em: Timestamp;
  id_usuario: number;
  id_verificacao: Generated<number>;
  token_hash: string;
}

export interface DB {
  aceite_termo_contribuicao: AceiteTermoContribuicao;
  area_conhecimento: AreaConhecimento;
  arquivo: Arquivo;
  arquivo_atualizacao: ArquivoAtualizacao;
  arquivo_recompensa: ArquivoRecompensa;
  atualizacao_campanha: AtualizacaoCampanha;
  auditoria_financeira: AuditoriaFinanceira;
  campanha: Campanha;
  comentario: Comentario;
  configuracoes: Configuracoes;
  contribuicao: Contribuicao;
  contribuicao_recompensa: ContribuicaoRecompensa;
  denuncia: Denuncia;
  historico_rejeicao: HistoricoRejeicao;
  link_academico: LinkAcademico;
  link_atualizacao: LinkAtualizacao;
  link_recompensa: LinkRecompensa;
  log_auditoria: LogAuditoria;
  marco_cronograma: MarcoCronograma;
  motivo_denuncia: MotivoDenuncia;
  notificacao: Notificacao;
  orcamento_campanha: OrcamentoCampanha;
  papel: Papel;
  papel_permissao: PapelPermissao;
  perfil_pesquisador: PerfilPesquisador;
  permissao: Permissao;
  recompensa: Recompensa;
  recuperacao_senha: RecuperacaoSenha;
  repasse: Repasse;
  score_config: ScoreConfig;
  score_pesquisador: ScorePesquisador;
  score_rotulo: ScoreRotulo;
  seguir_campanha: SeguirCampanha;
  seguir_pesquisador: SeguirPesquisador;
  sessao: Sessao;
  solicitacao_encerramento: SolicitacaoEncerramento;
  termos_de_uso: TermosDeUso;
  tipo_link: TipoLink;
  usuario: Usuario;
  usuario_papel: UsuarioPapel;
  usuario_termo: UsuarioTermo;
  verificacao_email: VerificacaoEmail;
}
