export const DENUNCIA_COLUNAS_SELECT = [
  'id_denuncia',
  'id_usuario',
  'id_campanha_alvo',
  'id_pesquisador_alvo',
  'id_motivo',
  'relato',
  'status',
  'justificativa_moderacao',
  'contestacao',
  'contestacao_status',
  'contestada_em',
  'justificativa_contestacao',
  'criado_em',
] as const;
